### ISSUE TITLE
Unable to create file 'CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rysias** [KennethEnevoldsen/swift-python-cookiecutter#5]
Howdy Kenneth, 

I was taking your template for a spin when I encountered the following error:

```
Unable to create file 'CONTRIBUTING.md'
Error message: 'collections.OrderedDict object' has no attribute 'license'
```

Do you have any good suggestions for how to resolve it?

**Comment by Rysias** [comment]
lol nvm, seems like Martin's repo works fine: https://github.com/MartinBernstorff/swift-python-cookiecutter

**Comment by KennethEnevoldsen** [comment]
Hej @Rysias, both Martin and I works with his repo så actually no need to use this repo. I will probably just delete it
